### ISSUE TITLE
Implement preview calculation & display.

### ISSUE THREAD

**Issue by muhuk** [muhuk/yer#29]
### Current Implementation Status

- In the current implementation flow is like `UI -> Action -> UndoEvent & LayerChange events fired`.
- There's a stand-in mesh that's added to the scene but it's not connected to preview system in any way.
- Preview config is not implemented yet.

### To-Do

- [x] Try removing `CreateLayer` & `DeleteLayer`  commands. (And use `undo::PushAction`).
- [x] See if `UndoEvent` could be enough to track layer changes. Having granular events is good but it might be hard to keep track.
- [x] Add preview settings data to the project.
- [x] Save/load preview settings.
- [x] Display preview settings in UI.
- [x] Remove the temporary quad added to the scene in `viewport::startup_system`.
- [x] Calculate and add preview mesh to the scene.

-----

See muhuk/yer#5
